#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN


hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 60000
#开启actuator管理api
management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/


spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: auth-service-route
          uri: lb://authenticationservice
          predicates:
            - Path=/auth/**
      default-filters:
        - name: Hystrix
          args:
            name: HystrixCommand
            fallbackUri: forward:/fallback




