server:
  port: 5555

management:
  endpoints:
    web:
      exposure:
        include: routes,filters,info,health

  #Setting logging levels
logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://discovery:8761/eureka/