security:
  oauth2:
    resource:
      userInfoUri: http://authenticationservice:8901/auth/user


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/


spring:
  redis:
    database: 5  # Redis数据库索引（默认为0）
    host: redis
    port: 6379
    password: "{cipher}4788dfe1ccbe6485934aec2ffeddb06163ea3d616df5fd75be96aadd4df1da91"
    jedis:
      pool:
        max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8  # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 0 # 连接超时时间（毫秒）
  cloud:
    stream:
      rocketmq:
        binder:
          name-server:
            rmqnamesrv:9876
      bindings:
        corpChanges:
          destination: corpChangeTopic
          content-type: application/json
          group: corpCache
        projectChanges:
          destination: projectChangeTopic
          content-type: application/json
          group: projectCache



