#性能参数调节  必要的地址设置

spring:
  datasource:
    initialization-mode: NEVER
    testWhileIdle: "true"
    validationQuery: "SELECT 1"
    url: "jdbc:mysql://database:3306/CONSTRUCT?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false"
    username: "root"
    password: "{cipher}4788dfe1ccbe6485934aec2ffeddb06163ea3d616df5fd75be96aadd4df1da91"
  jpa:
    show-sql: "false"
    properties:
      hibernate:
        ddl-auto: "none"
        enable_lazy_load_no_trans: true
        dialect: "org.hibernate.dialect.MySQL5Dialect"

