signing:
  key: "345345fsdfsf5345"

spring:
  datasource:
    initialization-mode: NEVER
    testWhileIdle: "true"
    validationQuery: "SELECT 1"
    url: "jdbc:mysql://database:3306/MONEY_ACCOUNT?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false"
    username: "root"
    password: "{cipher}4788dfe1ccbe6485934aec2ffeddb06163ea3d616df5fd75be96aadd4df1da91"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    database: "MYSQL"
    show-sql: "false"
    hibernate:
      naming:
        physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
    properties:
      hibernate:
        ddl-auto: "none"
        enable_lazy_load_no_trans: true
        dialect: "org.hibernate.dialect.MySQL5Dialect"
ugly:
  register:
    service:
      url: http://contractregisterservice:9901/api/