server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        native:
          searchLocations: file:///config/roomservice,file:///config/zuulservice,file:///config/authenticationservice,file:///config/businesstemplateservice,file:///config/archivesbusinessservice,file:///config/joincorpservice,file:///config/moneyaccountservice,file:///config/moneybankservice,file:///config/moneycorrectservice,file:///config/moneymodifyservice,file:///config/moneypayservice,file:///config/developerservice,file:///config/construct-attach-corp,file:///config/construct-project,file:///config/construct-project-cache,file:///config/construct-fire,file:///config/camundasvr,file:///config/businessdefinesvr

#          classpath:config/,

