security:
  oauth2:
    resource:
      userInfoUri: http://authenticationservice:8901/auth/user

camunda.bpm:
  database:
    schema-update: false
    type: mysql
  webapp:
    index-redirect-enabled: true
  admin-user:
    id: camunda
    password: Cooper&camunda
  authorization:
    enabled: true
  filter:
    create: All tasks

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/

spring:
  datasource:
    initialization-mode: NEVER
    testWhileIdle: "true"
    validationQuery: "SELECT 1"
    url: "jdbc:mysql://database:3306/camunda?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&nullDatabaseMeansCurrent=true&nullCatalogMeansCurrent=true"
    username: "root"
    password: "{cipher}4788dfe1ccbe6485934aec2ffeddb06163ea3d616df5fd75be96aadd4df1da91"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    database: "MYSQL"
    show-sql: "false"
    properties:
      hibernate:
        ddl-auto: "none"
        enable_lazy_load_no_trans: true
        dialect: "org.hibernate.dialect.MySQL5Dialect"
  cloud:
    stream:
      rocketmq:
        binder:
          name-server:
            rmqnamesrv:9876
      bindings:
        fireCheckBusiness:
          destination: fireCheckBusinessTopic
          content-type: application/json

uid:
  timeBits: 30             # 时间位, 默认:30
  workerBits: 17           # 机器位, 默认:16
  seqBits: 6               # 序列号, 默认:7
  epochStr: "2019-09-01"   # 初始时间, 默认:"2019-02-20"
  enableBackward: true    # 是否容忍时钟回拨, 默认:true
  maxBackwardSeconds: 1    # 时钟回拨最长容忍时间（秒）, 默认:1
  CachedUidGenerator:     # CachedUidGenerator相关参数
    boostPower: 3          # RingBuffer size扩容参数, 可提高UID生成的吞吐量, 默认:3
    paddingFactor: 50      # 指定何时向RingBuffer中填充UID, 取值为百分比(0, 100), 默认为50
    #scheduleInterval: 60    # 默认:不配置此项, 即不实用Schedule线程. 如需使用, 请指定Schedule线程时间间隔, 单位:秒

